### ISSUE TITLE
ENOENT error when write is false

### ISSUE THREAD

**Issue by beyerleinf** [craftamap/esbuild-plugin-html#23]
Hi, Love this plugin! Just notices one issue. I'm getting an `ENOENT` error when there is no `dist` directory yet. In my case, this happens because I need to have `esbuildConfig.write` set to false.

Here's the error:
```js
{
  pluginName: 'esbuild-html-plugin',
  text: "ENOENT: no such file or directory, open 'dist/index.html'",
  location: null,
  notes: [
    {
      text: 'This error came from the "onEnd" callback registered here:',
      location: {
        file: '/home/**********/node_modules/@craftamap/esbuild-plugin-html/lib/cjs/index.js',
        namespace: 'file',
        line: 40,
        column: 18,
        length: 5,
        lineText: '            build.onEnd(async (result) => {\n' +
          '    at setup (/home/**********/node_modules/@craftamap/esbuild-plugin-html/lib/cjs/index.js:40:19)\n' +
          '    at handlePlugins (/home/**********/node_modules/esbuild/lib/main.js:841:23)\n' +
          '    at Object.buildOrServe (/home/**********/node_modules/esbuild/lib/main.js:1135:7)\n' +
          '    at /home/**********/node_modules/esbuild/lib/main.js:2059:17\n' +
          '    at new Promise (<anonymous>)\n' +
          '    at Object.build (/home/**********/node_modules/esbuild/lib/main.js:2058:14)\n' +
          '    at build (/home/**********/node_modules/esbuild/lib/main.js:1912:51)\n' +
          '    at file:///home/**********/build.mjs:5:7',
        suggestion: ''
      }
    }
  ]
}
```

This is not a big issue, just wanted to point it out. If you don't want to fix it, that's fine with me 😊

P.S.: If you ever need help with anything, let me know!

**Comment by craftamap** [comment]
Hey Fabian! Thanks for reporting this! I noticed this recently as well, and will work on a fix :)
