### ISSUE TITLE
Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by ike-yu-byte** [craftamap/esbuild-plugin-html#54]
X [ERROR] Cannot read property 'version' of undefined [plugin esbuild-html-plugin]

    D:\my_test\myNode\esbuild\vue\node_modules\lodash.template\index.js:1550:11:
      1550 │     return Function(importsKeys, sourceURL + 'return ' + source)
           ╵            ^

    at eval (eval at <anonymous> (D:\my_test\myNode\esbuild\vue\node_modules\lodash.template\index.js:1550:12), <anonymous>:8:13)
    at renderTemplate (D:\my_test\myNode\esbuild\vue\node_modules\@craftamap\esbuild-plugin-html\lib\cjs\index.js:103:16)        
    at D:\my_test\myNode\esbuild\vue\node_modules\@craftamap\esbuild-plugin-html\lib\cjs\index.js:246:52
    at D:\my_test\myNode\esbuild\vue\node_modules\esbuild\lib\main.js:1496:33
    at runOnEndCallbacks (D:\my_test\myNode\esbuild\vue\node_modules\esbuild\lib\main.js:1528:9)
    at buildResponseToResult (D:\my_test\myNode\esbuild\vue\node_modules\esbuild\lib\main.js:1057:7)
    at D:\my_test\myNode\esbuild\vue\node_modules\esbuild\lib\main.js:1069:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (D:\my_test\myNode\esbuild\vue\node_modules\esbuild\lib\main.js:1068:54)
    at handleRequest (D:\my_test\myNode\esbuild\vue\node_modules\esbuild\lib\main.js:732:17)

  This error came from the "onEnd" callback registered here:

    D:\my_test\myNode\esbuild\vue\node_modules\@craftamap\esbuild-plugin-html\lib\cjs\index.js:213:18:
      213 │             build.onEnd(async (result) => {
          ╵                   ~~~~~

    at setup (D:\my_test\myNode\esbuild\vue\node_modules\@craftamap\esbuild-plugin-html\lib\cjs\index.js:213:19)
    at handlePlugins (D:\my_test\myNode\esbuild\vue\node_modules\esbuild\lib\main.js:1293:21)
    at buildOrContextImpl (D:\my_test\myNode\esbuild\vue\node_modules\esbuild\lib\main.js:979:5)
    at Object.buildOrContext (D:\my_test\myNode\esbuild\vue\node_modules\esbuild\lib\main.js:788:5)
    at D:\my_test\myNode\esbuild\vue\node_modules\esbuild\lib\main.js:2224:68
    at new Promise (<anonymous>)
    at Object.context (D:\my_test\myNode\esbuild\vue\node_modules\esbuild\lib\main.js:2224:27)
    at Object.context (D:\my_test\myNode\esbuild\vue\node_modules\esbuild\lib\main.js:2048:58)
    at file:///D:/my_test/myNode/esbuild/vue/scripts/dev.ts:24:35

**Comment by craftamap** [comment]
Hey - is this still a problem you are running into?
